### ISSUE TITLE
US 01.04.01 organizer can upload event poster

### ISSUE THREAD

**Issue by aveeran** [CMPUT301W24T32/brazmas#8]
US 01.04.01 As an organizer, I want to upload an event poster to provide visual information to attendees.

Acceptance Criteria:
1. The organizer is able to create an event AND modify existing events, having changes reflected in the database.
2. The organizer is able to see a button that allows them to upload an event poster
3. The organizer is able to see a collection of choices to upload as the event poster (photos from their own device)
4. The organizer is able to upload an event poster
5. The submitted event poster is uploaded to the database

Story Points (1-10): 6

Risk: Medium

**Comment by meharklair** [comment]
1. OrganizerAddEditEventFragment
2. upload poster
